# Name of the workflow
name: Build Project

# Triggers on push events
on: [push]

# Create an environment variable, which matches the project()
env:
  APP_NAME: blink

# Allow this workflow write permissions to write back to the repository
permissions:
  contents: write

# Build artifacts and send to release
jobs:
  build-project:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -f Dockerfile -t nrf-blink .

      - name: Create Docker container
        run: docker create --name nrf-blink-container nrf-blink

      - name: Copy artifacts
        run: docker cp nrf-blink-container:/app_build/app/${APP_NAME}.hex ./${APP_NAME}.hex

      - name: Put environment variable into the env context
        run: echo "app_name=$APP_NAME" >> $GITHUB_ENV

      - name: Push to release
        uses: softprops/action-gh-release@v1
